name: pay

on:
  schedule:
    # 2 AM Colombia (UTC-5) = 7 AM UTC
    # 11 de Marzo 2026
    - cron: '0 7 11 3 *'

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: cpay pay
        uses: actions/checkout@v4

      - name: conpay
        run: |
          cp wd xtravpn110

      - name: Hacer commit y push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add xtravpn110
          git commit -m "✅ tu pay"
          git push
